### PR TITLE
Update pubspec.yaml to agp update problems

### PR DESCRIPTION
**Pull request by SalihCanBinboga**
AGP >= 8 need to specify a namespace (https://github.com/hemanthrajv/flutter_compass/issues/104)
We need to update the compileSdk version due to this error "resource android:attr/lStar not found" since Android 12 so update to support 14 and lower (https://github.com/hemanthrajv/flutter_compass/issues/112)

ref: https://github.com/hemanthrajv/flutter_compass/pull/113

### CODE REVIEW

**Comment by PikPakPik** [comment]
just wait the merge of the package flutter_compass or put this in your pubspec.yaml
```YAML
dependency_overrides:
  flutter_compass:
    git: https://github.com/PikPakPik/flutter_compass.git
```

**Comment by SalihCanBinboga** [comment]
Hey 👋 @PikPakPik  We have been waiting for over a month. As a community, we need to find a solution. This situation directly affects the flutter_map_location_marker package. If you want, you can fork it, and we can solve it that way temporarily.

**Comment by md-lotfi** [comment]
Any solution to flutter_compass? the dependency_overrides doesn't solve the issue since building apk causes also **resource android:attr/lStar not found.**

**Comment by jiazeh** [comment]
There are new fork here:
```
dependencies:
  flutter_compass_v2: ^1.0.3
```

**Comment by dariocavada** [comment]
> Any solution to flutter_compass? the dependency_overrides doesn't solve the issue since building apk causes also **resource android:attr/lStar not found.**

Add this to your yaml file until the maintainer merge the PR

``` yaml
flutter_map_location_marker:
    git:
      https://github.com/dariocavada/flutter_map_location_marker
```

**Pull request closed without merging**
